services:
  - type: web
    name: medicare-hms-free
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: DB_DRIVER
        value: pgsql
      - key: DB_SSL
        value: "true"
      - key: APP_URL
        value: https://medicare-hms-free.onrender.com
      - key: FRONTEND_URL
        value: https://medicare-hms.vercel.app
      - key: ADMIN_PATH
        value: mgmt-x7k2p
      - key: ADMIN_ALLOWED_IPS
        sync: false
      - key: STAFF_ALLOWED_IPS
        sync: false
      - key: TRUSTED_PROXY_IPS
        sync: false
      - key: APP_ENCRYPTION_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
