-- =====================================================
-- Hospital Management System (HMS) - PostgreSQL 16 production schema
-- High-Performance Enterprise Relational Schema for Local MySQL
-- =====================================================

-- 1. USERS
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    role VARCHAR(50) NOT NULL,
    avatar VARCHAR(255) DEFAULT NULL,
    status VARCHAR(50) DEFAULT 'active',
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_secret TEXT DEFAULT NULL,
    mfa_backup_codes TEXT DEFAULT NULL,
    mfa_enrolled_at TIMESTAMP DEFAULT NULL,
    last_login TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_devices (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    label VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP DEFAULT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP DEFAULT NULL
);

-- 2. DEPARTMENTS
CREATE TABLE IF NOT EXISTS departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    head_doctor_id INT DEFAULT NULL,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. PATIENTS
CREATE TABLE IF NOT EXISTS patients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    uhid VARCHAR(20) NOT NULL UNIQUE,
    date_of_birth DATE DEFAULT NULL,
    gender VARCHAR(50) DEFAULT NULL,
    blood_group VARCHAR(10) DEFAULT '',
    marital_status VARCHAR(20) DEFAULT '',
    address TEXT,
    city VARCHAR(50) DEFAULT NULL,
    state VARCHAR(50) DEFAULT NULL,
    zip_code VARCHAR(10) DEFAULT NULL,
    emergency_contact_name VARCHAR(100) DEFAULT NULL,
    emergency_contact_phone VARCHAR(20) DEFAULT NULL,
    emergency_contact_relation VARCHAR(50) DEFAULT NULL,
    insurance_provider VARCHAR(100) DEFAULT NULL,
    insurance_number VARCHAR(50) DEFAULT NULL,
    allergies TEXT,
    chronic_conditions TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_patients_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. DOCTORS
CREATE TABLE IF NOT EXISTS doctors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    department_id INT DEFAULT NULL,
    specialization VARCHAR(100) DEFAULT NULL,
    qualification VARCHAR(200) DEFAULT NULL,
    license_number VARCHAR(50) DEFAULT NULL,
    experience_years INT DEFAULT 0,
    consultation_fee DECIMAL(10,2) DEFAULT 0.00,
    bio TEXT,
    schedule TEXT,
    max_patients_per_day INT DEFAULT 30,
    status VARCHAR(10) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doctors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_doctors_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);

-- 5. WARDS
CREATE TABLE IF NOT EXISTS wards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) DEFAULT 'general',
    floor INT DEFAULT 1,
    capacity INT DEFAULT 10,
    description TEXT,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. NURSES
CREATE TABLE IF NOT EXISTS nurses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    ward_id INT DEFAULT NULL,
    shift VARCHAR(50) DEFAULT 'morning',
    qualification VARCHAR(200) DEFAULT NULL,
    experience_years INT DEFAULT 0,
    status VARCHAR(10) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nurses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_nurses_ward FOREIGN KEY (ward_id) REFERENCES wards(id) ON DELETE SET NULL
);

-- 7. BEDS
CREATE TABLE IF NOT EXISTS beds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id INT NOT NULL,
    bed_number VARCHAR(20) NOT NULL,
    status VARCHAR(50) DEFAULT 'available',
    daily_charge DECIMAL(10,2) DEFAULT 0.00,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ward_bed UNIQUE (ward_id, bed_number),
    CONSTRAINT fk_beds_ward FOREIGN KEY (ward_id) REFERENCES wards(id) ON DELETE CASCADE
);

-- 8. APPOINTMENTS
CREATE TABLE IF NOT EXISTS appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    department_id INT DEFAULT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    status VARCHAR(50) DEFAULT 'scheduled',
    token_number INT DEFAULT NULL,
    type VARCHAR(50) DEFAULT 'opd',
    reason TEXT,
    notes TEXT,
    created_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_app_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    CONSTRAINT fk_app_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- 9. ADMISSIONS
CREATE TABLE IF NOT EXISTS admissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    bed_id INT DEFAULT NULL,
    ward_id INT DEFAULT NULL,
    admit_date TIMESTAMP NOT NULL,
    expected_discharge DATE DEFAULT NULL,
    discharge_date TIMESTAMP DEFAULT NULL,
    status VARCHAR(50) DEFAULT 'admitted',
    reason TEXT,
    discharge_summary TEXT,
    discharge_instructions TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adm_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
    CONSTRAINT fk_adm_bed FOREIGN KEY (bed_id) REFERENCES beds(id) ON DELETE SET NULL,
    CONSTRAINT fk_adm_ward FOREIGN KEY (ward_id) REFERENCES wards(id) ON DELETE SET NULL
);

-- 10. MEDICAL RECORDS
CREATE TABLE IF NOT EXISTS medical_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    appointment_id INT DEFAULT NULL,
    admission_id INT DEFAULT NULL,
    diagnosis TEXT,
    symptoms TEXT,
    clinical_notes TEXT,
    examination_findings TEXT,
    treatment_plan TEXT,
    follow_up_date DATE DEFAULT NULL,
    record_type VARCHAR(50) DEFAULT 'opd',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mr_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_mr_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
    CONSTRAINT fk_mr_app FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT fk_mr_adm FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE SET NULL
);

-- 11. PRESCRIPTIONS
CREATE TABLE IF NOT EXISTS prescriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_record_id INT DEFAULT NULL,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    appointment_id INT DEFAULT NULL,
    notes TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rx_mr FOREIGN KEY (medical_record_id) REFERENCES medical_records(id) ON DELETE SET NULL,
    CONSTRAINT fk_rx_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_rx_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
    CONSTRAINT fk_rx_app FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL
);

-- 12. PRESCRIPTION ITEMS
CREATE TABLE IF NOT EXISTS prescription_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id INT NOT NULL,
    drug_name VARCHAR(200) NOT NULL,
    dosage VARCHAR(100) DEFAULT NULL,
    frequency VARCHAR(100) DEFAULT NULL,
    duration VARCHAR(50) DEFAULT NULL,
    route VARCHAR(50) DEFAULT 'oral',
    instructions TEXT,
    quantity INT DEFAULT 0,
    CONSTRAINT fk_rxi_rx FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE CASCADE
);

-- 13. VITALS
CREATE TABLE IF NOT EXISTS vitals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    admission_id INT DEFAULT NULL,
    appointment_id INT DEFAULT NULL,
    nurse_id INT DEFAULT NULL,
    blood_pressure_systolic INT DEFAULT NULL,
    blood_pressure_diastolic INT DEFAULT NULL,
    temperature DECIMAL(4,1) DEFAULT NULL,
    pulse INT DEFAULT NULL,
    respiration_rate INT DEFAULT NULL,
    oxygen_saturation DECIMAL(5,2) DEFAULT NULL,
    blood_sugar DECIMAL(6,2) DEFAULT NULL,
    weight DECIMAL(5,2) DEFAULT NULL,
    height DECIMAL(5,2) DEFAULT NULL,
    bmi DECIMAL(5,2) DEFAULT NULL,
    notes TEXT,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vitals_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_vitals_adm FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE SET NULL,
    CONSTRAINT fk_vitals_app FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT fk_vitals_nurse FOREIGN KEY (nurse_id) REFERENCES nurses(id) ON DELETE SET NULL
);

-- 14. MEDICATION ADMINISTRATION
CREATE TABLE IF NOT EXISTS medication_administration (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   admission_id INT NOT NULL,
   patient_id INT NOT NULL,
   nurse_id INT NOT NULL,
   prescription_item_id INT DEFAULT NULL,
   drug_name VARCHAR(200) NOT NULL,
   dosage VARCHAR(100) DEFAULT NULL,
   scheduled_time TIMESTAMP DEFAULT NULL,
   administered_at TIMESTAMP DEFAULT NULL,
   status VARCHAR(15) DEFAULT 'pending',
   notes TEXT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_ma_admission FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE,
   CONSTRAINT fk_ma_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
   CONSTRAINT fk_ma_nurse FOREIGN KEY (nurse_id) REFERENCES nurses(id) ON DELETE CASCADE,
   CONSTRAINT fk_ma_item FOREIGN KEY (prescription_item_id) REFERENCES prescription_items(id) ON DELETE SET NULL
);

-- 15. NURSING NOTES
CREATE TABLE IF NOT EXISTS nursing_notes (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   admission_id INT NOT NULL,
   patient_id INT NOT NULL,
   nurse_id INT NOT NULL,
   note TEXT NOT NULL,
   priority VARCHAR(10) DEFAULT 'normal',
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_nn_admission FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE,
   CONSTRAINT fk_nn_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
   CONSTRAINT fk_nn_nurse FOREIGN KEY (nurse_id) REFERENCES nurses(id) ON DELETE CASCADE
);

-- 16. PHARMACY INVENTORY
CREATE TABLE IF NOT EXISTS pharmacy_inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_name VARCHAR(200) NOT NULL,
    generic_name VARCHAR(200) DEFAULT NULL,
    category VARCHAR(50) DEFAULT NULL,
    manufacturer VARCHAR(100) DEFAULT NULL,
    batch_number VARCHAR(50) DEFAULT NULL,
    stock_quantity INT DEFAULT 0,
    unit VARCHAR(20) DEFAULT 'pcs',
    unit_price DECIMAL(10,2) DEFAULT 0.00,
    selling_price DECIMAL(10,2) DEFAULT 0.00,
    expiry_date DATE DEFAULT NULL,
    reorder_level INT DEFAULT 10,
    storage_location VARCHAR(100) DEFAULT NULL,
    requires_prescription SMALLINT DEFAULT 1,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 17. PHARMACY DISPENSING
CREATE TABLE IF NOT EXISTS pharmacy_dispensing (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id INT NOT NULL,
    prescription_item_id INT DEFAULT NULL,
    drug_id INT DEFAULT NULL,
    drug_name VARCHAR(200) NOT NULL,
    quantity_dispensed INT NOT NULL,
    pharmacist_id INT NOT NULL,
    notes TEXT,
    dispensed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pd_prescription FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE CASCADE,
    CONSTRAINT fk_pd_item FOREIGN KEY (prescription_item_id) REFERENCES prescription_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_pd_drug FOREIGN KEY (drug_id) REFERENCES pharmacy_inventory(id) ON DELETE SET NULL,
    CONSTRAINT fk_pd_pharmacist FOREIGN KEY (pharmacist_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 18. LAB TEST CATALOG
CREATE TABLE IF NOT EXISTS lab_test_catalog (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name VARCHAR(200) NOT NULL,
    test_code VARCHAR(20) UNIQUE DEFAULT NULL,
    category VARCHAR(50) DEFAULT NULL,
    description TEXT,
    sample_type VARCHAR(50) DEFAULT NULL,
    price DECIMAL(10,2) DEFAULT 0.00,
    turnaround_time VARCHAR(50) DEFAULT NULL,
    normal_range TEXT,
    instructions TEXT,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 16. LAB ORDERS
CREATE TABLE IF NOT EXISTS lab_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    appointment_id INT DEFAULT NULL,
    admission_id INT DEFAULT NULL,
    test_id INT NOT NULL,
    priority VARCHAR(50) DEFAULT 'normal',
    status VARCHAR(50) DEFAULT 'ordered',
    clinical_notes TEXT,
    ordered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lo_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_lo_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
    CONSTRAINT fk_lo_app FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT fk_lo_adm FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE SET NULL,
    CONSTRAINT fk_lo_test FOREIGN KEY (test_id) REFERENCES lab_test_catalog(id) ON DELETE CASCADE
);

-- 17. LAB RESULTS
CREATE TABLE IF NOT EXISTS lab_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_order_id INT NOT NULL UNIQUE,
    result_value TEXT,
    result_unit VARCHAR(50) DEFAULT NULL,
    reference_range VARCHAR(100) DEFAULT NULL,
    interpretation VARCHAR(20) DEFAULT '',
    result_notes TEXT,
    attachments TEXT,
    technician_id INT DEFAULT NULL,
    verified_by INT DEFAULT NULL,
    verified_at TIMESTAMP DEFAULT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lr_order FOREIGN KEY (lab_order_id) REFERENCES lab_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_lr_tech FOREIGN KEY (technician_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_lr_ver FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL
);

-- 18. BILLING
CREATE TABLE IF NOT EXISTS billing (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT NOT NULL,
    appointment_id INT DEFAULT NULL,
    admission_id INT DEFAULT NULL,
    invoice_number VARCHAR(30) NOT NULL UNIQUE,
    subtotal DECIMAL(12,2) DEFAULT 0.00,
    discount DECIMAL(12,2) DEFAULT 0.00,
    tax DECIMAL(12,2) DEFAULT 0.00,
    net_amount DECIMAL(12,2) DEFAULT 0.00,
    payment_status VARCHAR(50) DEFAULT 'unpaid',
    payment_method VARCHAR(100) DEFAULT 'cash',
    payment_date TIMESTAMP DEFAULT NULL,
    insurance_claim_status VARCHAR(20) DEFAULT '',
    notes TEXT,
    created_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bill_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_bill_app FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT fk_bill_adm FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE SET NULL,
    CONSTRAINT fk_bill_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- 19. BILLING ITEMS
CREATE TABLE IF NOT EXISTS billing_items (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   bill_id INT NOT NULL,
   item_type VARCHAR(20) NOT NULL,
   description VARCHAR(255) NOT NULL,
   quantity INT DEFAULT 1,
   unit_price DECIMAL(10,2) DEFAULT 0.00,
   total_price DECIMAL(10,2) DEFAULT 0.00,
   reference_id INT DEFAULT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_bi_bill FOREIGN KEY (bill_id) REFERENCES billing(id) ON DELETE CASCADE
);

-- 20. AUDIT LOGS
CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT DEFAULT NULL,
    user_name VARCHAR(100) DEFAULT NULL,
    action VARCHAR(50) NOT NULL,
    table_name VARCHAR(50) DEFAULT NULL,
    record_id INT DEFAULT NULL,
    description TEXT,
    old_values TEXT,
    new_values TEXT,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 21. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT,
    type VARCHAR(50) DEFAULT 'info',
    link VARCHAR(255) DEFAULT NULL,
    is_read SMALLINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 22. SERVICE PRICING
CREATE TABLE IF NOT EXISTS service_pricing (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(200) NOT NULL,
    category VARCHAR(50) DEFAULT NULL,
    price DECIMAL(10,2) NOT NULL,
    description TEXT,
    status VARCHAR(10) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 23. PAYMENT METHODS
CREATE TABLE IF NOT EXISTS payment_methods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    account_name VARCHAR(100) DEFAULT NULL,
    account_number VARCHAR(100) DEFAULT NULL,
    qr_image TEXT DEFAULT NULL,
    instructions TEXT,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 24. PASSWORD RESETS
CREATE TABLE IF NOT EXISTS password_resets (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id INT NOT NULL,
   token VARCHAR(64) UNIQUE NOT NULL,
   expires_at TIMESTAMP NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_pr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 25. REFRESH TOKENS (JWT Decoupled Authentication)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked SMALLINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent TEXT,
    CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 24. PERFORMANCE INDEXES
CREATE INDEX idx_appointments_date_status ON appointments (appointment_date, status);
CREATE INDEX idx_appointments_patient ON appointments (patient_id);
CREATE INDEX idx_appointments_doctor ON appointments (doctor_id);
CREATE INDEX idx_billing_created_status ON billing (created_at, payment_status);
CREATE INDEX idx_billing_patient ON billing (patient_id);
CREATE INDEX idx_prescriptions_created_status ON prescriptions (created_at, status);
CREATE INDEX idx_prescriptions_patient ON prescriptions (patient_id);
CREATE INDEX idx_lab_orders_date_status ON lab_orders (ordered_at, status);
CREATE INDEX idx_lab_orders_patient ON lab_orders (patient_id);
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX idx_patients_created ON patients (created_at);
CREATE INDEX idx_password_resets_token_exp ON password_resets (token, expires_at);
CREATE INDEX idx_pharmacy_inv_name_status ON pharmacy_inventory (drug_name, status);
CREATE INDEX idx_refresh_tokens_hash_exp ON refresh_tokens (token_hash, expires_at, revoked);
CREATE INDEX idx_users_phone ON users(phone);
CREATE INDEX idx_departments_status_name ON departments(status, name);
CREATE INDEX idx_medical_records_patient_created ON medical_records(patient_id, created_at DESC);
CREATE INDEX idx_prescription_items_prescription ON prescription_items(prescription_id);
CREATE INDEX idx_vitals_patient_recorded ON vitals(patient_id, recorded_at DESC);
CREATE INDEX idx_lab_orders_status_ordered ON lab_orders(status, ordered_at);
CREATE INDEX idx_lab_results_order ON lab_results(lab_order_id);
CREATE INDEX idx_billing_items_bill ON billing_items(bill_id);
CREATE INDEX idx_billing_patient_status_id ON billing(patient_id, payment_status, id);
CREATE INDEX idx_pharmacy_inv_status_stock ON pharmacy_inventory(status, stock_quantity, reorder_level);
CREATE INDEX idx_lab_catalog_status_category_name ON lab_test_catalog(status, category, test_name);
CREATE INDEX idx_service_pricing_status_category_name ON service_pricing(status, category, service_name);

-- DB-backed sessions (SESSION_DRIVER=db) for serverless/multi-instance deploys
CREATE TABLE IF NOT EXISTS app_sessions (
    id VARCHAR(128) PRIMARY KEY,
    data TEXT NOT NULL,
    last_accessed BIGINT NOT NULL
);
CREATE INDEX idx_app_sessions_last_accessed ON app_sessions(last_accessed);
